export const actionTypes = {
     FETCHING_START: "FETCHING_START",
     FETCHING_SUCCESS: "FETCHING_SUCCESS",
     FETCHING_ERROR: "FETCHING_ERROR",
     ADD_TO_CART: "ADD_TO_CART",
     ADD_WISH_LIST: "ADD_WISH_LIST",
     REMOVE_CART: "REMOVE_CART",
};